spring.datasource.url=jdbc:mysql://localhost:3306/cash_2_carat
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mySuperSecretKey
jwt.expiration=86400000